-- Cleaning up any duplicate signatures to avoid ambiguity
DROP FUNCTION IF EXISTS record_usage(TEXT, TEXT, NUMERIC, NUMERIC, JSONB, TEXT);
DROP FUNCTION IF EXISTS record_usage(UUID, TEXT, TEXT, NUMERIC, NUMERIC, JSONB);
DROP FUNCTION IF EXISTS record_usage(TEXT, TEXT, TEXT, NUMERIC, NUMERIC, JSONB);
DROP FUNCTION IF EXISTS record_usage(UUID, UUID, TEXT, NUMERIC, NUMERIC, JSONB);
