-- Query to check messages for the NEW conversation ID
-- conversation_id: d2d977c4-5653-42e8-94c3-b2dafea10a89 (Generated by V15)

SELECT 
    id,
    conversation_id,
    sender_type,
    content,
    external_order,
    external_id,
    metadata
FROM messages 
WHERE conversation_id = 'd2d977c4-5653-42e8-94c3-b2dafea10a89';

-- Check if messages exist for the SAME call_id but DIFFERENT conversation
-- This would explain why ON CONFLICT DO NOTHING is hitting, but 0 are inserted for THIS conversation
SELECT conversation_id, COUNT(*) as msg_count 
FROM messages 
WHERE external_id LIKE '019c3a3e-6f26-7ee9-acdf-e9b25279e59a-%'
GROUP BY conversation_id;
